### ISSUE TITLE
请问一下  docker怎么把配置文件映射出来了

### ISSUE THREAD

**Issue by jt8823** [VergilGao/docker-mdc#29]
我用的群晖docker
config.ini的装载地址是什么啊

我在docker -编辑-环境  里配置   好像有问题
不知道什么情况

**Comment by jt8823** [comment]
LOCATION_RULE              "actor+'/'+number"
我想把这一项改成   只有番号  一层文件夹   
需要怎么修改啊

**Comment by VergilGao** [comment]
"number"

**Comment by jt8823** [comment]
> "number"

这个我试了。不对啊。     在环境中修改后
名称就变成number了。就这这个单词。  不是番号

**Comment by VergilGao** [comment]
我没用过群晖，我启动docker镜像用下面这个命令
```docker run --rm --name avdc -it -v ${PWD}:/app/data -e LOCATION_RULE="number" vergilgao/avdc:latest```

**Comment by jt8823** [comment]
> 我没用过群晖，我启动docker镜像用下面这个命令
> `docker run --rm --name avdc -it -v ${PWD}:/app/data -e LOCATION_RULE="number" vergilgao/avdc:latest`
> 是没有问题的

谢谢   通过ssh  我也试了    效果还是一样的   不行
然后我试了一下  windows版本的   修改  config.ini  竟然可以。。
