### ISSUE TITLE
UnRaid系统Docker模板

### ISSUE THREAD

**Issue by gmy771810930** [VergilGao/docker-mdc#33]
1.把my-AV_Data_Capture.xml.txt的后缀.txt去掉，改成.xml文件
2.把这个文件上传到 /boot/config/plugins/dockerMan/templates-user 目录下，也就是启动U盘的/config/plugins/dockerMan/templates-user 目录下
3.docker添加容器，选择AV_Data_Capture模板
[my-AV_Data_Capture.xml.txt](https://github.com/VergilGao/docker-avdc/files/7357628/my-AV_Data_Capture.xml.txt)

注：刮预告片的开关没有用，这个得等作者适配。

**Comment by VergilGao** [comment]
由于版本改动，此模板失效。
