### ISSUE TITLE
最近搜刮的封面有问题

### ISSUE THREAD

**Issue by zhujun99170** [VergilGao/docker-mdc#36]
最近搜刮的封面怎么都是乱七八糟的画面，没有居中的人像。看了搜刮的几个文件，大小都一样，以前好像是封面的文件要小一些。

**Comment by VergilGao** [comment]
最近比较忙没有时间同步上游，这个版本的确有些问题，可以考虑选择一个旧版本来使用。

**Comment by zhujun99170** [comment]
好的好的，老大辛苦。
