### ISSUE TITLE
docker版本已经删除了吗，dockerhub上已经搜不到了。。

### ISSUE THREAD

**Issue by e68862230** [VergilGao/docker-mdc#39]
求解。。

**Comment by VergilGao** [comment]
更新了6.0.1
现在同时存在2个repo：
vergilgao/avdc
vergilgao/mdc
因为上游仓库更名，未来将会逐步弃用vergilgao/avdc这个repo
同时由于docker hub的限制，我将会增加对ghcr.io的支持，并且如果docker hub的限制进一步增加，我可能会考虑放弃对docker hub的支持。
