### ISSUE TITLE
SSL 错误？

### ISSUE THREAD

**Issue by lunaeidolon** [VergilGao/docker-mdc#41]
[-]HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /yoshiko2/Movie_Data_Capture/master/MappingTable/c_number.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))) | stdout
-- | --

**Comment by VergilGao** [comment]
换个好点的梯子试一下。
