### ISSUE TITLE
能否支持PUID和PGID环境变量，用某个用户去运行docker

### ISSUE THREAD

**Issue by NagaseKouichi** [VergilGao/docker-mdc#42]
Unraid上的samba用户不是root，但是docker默认是用root账号运行，导致刮削后的文件是root权限，不能使用samba用户去管理，只能使用SSH管理。

能否指定PUID和PGID，让docker使用samba那个账号去运行，方便使用samba用户管理？

**Comment by VergilGao** [comment]
要实现这个功能需要集成 s6-overlay
或者改用 lsiobase/python 作为基础镜像

可以实现，有时间我研究一下。

**Comment by NagaseKouichi** [comment]
大佬辛苦了。今天我测试了很久，发现这个是目前最大的痛点了，搜了一下issues里面好像之前没有人提过，不知道大家之前都怎么解决的。

**Comment by VergilGao** [comment]
已完成。

**Comment by NagaseKouichi** [comment]
> 已完成。

感谢大佬！

**Comment by VergilGao** [comment]
这两天可能还要改一下，把s6的依赖干掉，因为我发现了更好的办法来实现。
