### ISSUE TITLE
最新的版本开启不了，报错如下

### ISSUE THREAD

**Issue by skypjsfly** [VergilGao/docker-mdc#43]
![QQ截图20220209214833](https://user-images.githubusercontent.com/32484309/153214098-8657777a-6800-4e2a-a73e-b6d3a904abc2.png)
![QQ截图20220209214854](https://user-images.githubusercontent.com/32484309/153214133-763a7792-0a97-4f20-a9fc-12991f743aac.png)

**Comment by skypjsfly** [comment]
运行环境群晖1621，cpu V1500B

**Comment by VergilGao** [comment]
你没有挂载目录到 /data 么？

**Comment by skypjsfly** [comment]
肯定是挂载了啊，另外，我都不知道用户id和组id去哪查
![QQ截图20220209221156](https://user-images.githubusercontent.com/32484309/153218286-d0cb45f5-b8d2-40ad-a796-bfa89bc88c28.png)

**Comment by skypjsfly** [comment]
另外，我刚测试，一个不挂载目录，一个挂载新建的目录，日志分别如图
![QQ截图20220209221404](https://user-images.githubusercontent.com/32484309/153218735-516d6dfe-119a-46ce-8189-513f27309af0.png)

**Comment by skypjsfly** [comment]
如果挂载/app/data，日志如图，好像能正常运行。但是显示没有媒体文件
![QQ截图20220209221647](https://user-images.githubusercontent.com/32484309/153219196-a75bad64-cf37-4be5-9969-a7ed10b3a9f2.png)
但是挂载/data，就像之前反馈的那样

**Comment by VergilGao** [comment]
我手头没有测试环境，我更新了一下docker镜像，你可以用最新的镜像试一下。
挂载点是 /data

**Comment by Johnhpure** [comment]
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/26353341/153335579-4ab63fb8-dd12-48d5-8c75-420b8d8e782f.png">
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/26353341/153335635-6c45949a-fe45-460e-87ba-67d5e27e8524.png">
同样存在此问题，黑群，docker，docker pull vergilgao/avdc:6.0.1拉取最新的镜像
启动时报错见截图

**Comment by Johnhpure** [comment]
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/26353341/153336332-405b334a-7529-4bdf-9874-21c712ee3e51.png">
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/26353341/153336359-ed4e558b-dd70-4319-9f11-e5f6cdb3bd49.png">
<img width="706" alt="image" src="https://user-images.githubusercontent.com/26353341/153336511-5e4df983-f6fb-4560-90b1-10f32003c1fd.png">

经测试，将挂在目录更换为/app/data可正常运行，但报网络错误，我已经按照要求增加了代理url，请教一下问题出在哪里呢？

**Comment by VergilGao** [comment]
你用错镜像了，最新的是 vergilgao/mdc

**Comment by skypjsfly** [comment]
> 我手头没有测试环境，我更新了一下docker镜像，你可以用最新的镜像试一下。 挂载点是 /data

刚测试了，还是不行，测试了两次，日志上面部分映射的是/app/data，下面映射的是/data
![Screenshot_20220210-141819_Via](https://user-images.githubusercontent.com/32484309/153349499-b640d4a8-6b4d-4fd9-b358-efb14505c8fd.png)

**Comment by skypjsfly** [comment]
> 你用错镜像了，因为上游仓库改名，目前维持更新的是 vergilgao/mdc
> 
> 此外我没用过代理功能，所以我也不知道，你可以去主仓库求助

映射/app/data文件夹，能正常运行，但是脚本不到媒体文件，说明程序不从这个文件夹读取媒体文件，映射/data出错，我猜测/data应该不是空文件夹，是不是里面还有什么配置文件，所以报错了？

**Comment by VergilGao** [comment]
你挂载的目录是不是有 config.ini 文件？

**Comment by skypjsfly** [comment]
> 你挂载的目录是不是有 config.ini 文件？

没有，空文件夹

**Comment by VergilGao** [comment]
你如果有条件，可以进终端打命令， id 命令可以获取你的 userid 和groupid，然后在环境变量里设置UID和GID，再原地输入命令
···
mkdir test
dd if=/dev/zero of="./test/MIFD-046.mp4" bs=250MB count=1
···
再输入 pwd 命令可以获取你现在的目录
然后你把这个目录下的 test 文件夹映射进去

**Comment by VergilGao** [comment]
> > 你如果有条件，可以进终端打命令， id 命令可以获取你的 userid 和groupid，然后在环境变量里设置UID和GID，再原地输入命令 ··· mkdir test dd if=/dev/zero of="./test/MIFD-046.mp4" bs=250MB count=1 ··· 再输入 pwd 命令可以获取你现在的目录 然后你把这个目录下的 test 文件夹映射进去
> 
> 看着有点懵。。。主要是我之前的版本一直是正常使用的，就昨天更新的版本突然用不了了

因为不同的系统的文件权限设计不一样，我特意设置的 PUID 和 PGID 环境变量就是为了适应不同系统的文件权限设计。
比如 unraid 默认所有文件都属于 nobody:nusers 通过设置 PUID 和 PGID 就可以让容器运行之后的效果符合 unraid 的设计，这样就不需要额外的修复权限操作。

而此前的版本最终生成的文件默认情况下属于 root 用户

但是群晖很可能默认情况下，运行docker容器的用户不是root，也不是当前用户（具体是哪个用户因为我没用过群晖我也不知道），而默认建立文件夹的用户也不知道是哪个用户，所以我现在无法给你一个解决方案。

**Comment by skypjsfly** [comment]
> > > 你如果有条件，可以进终端打命令， id 命令可以获取你的 userid 和groupid，然后在环境变量里设置UID和GID，再原地输入命令 ··· mkdir test dd if=/dev/zero of="./test/MIFD-046.mp4" bs=250MB count=1 ··· 再输入 pwd 命令可以获取你现在的目录 然后你把这个目录下的 test 文件夹映射进去
> > 
> > 
> > 看着有点懵。。。主要是我之前的版本一直是正常使用的，就昨天更新的版本突然用不了了
> 
> 因为不同的系统的文件权限设计不一样，我特意设置的 PUID 和 PGID 环境变量就是为了适应不同系统的文件权限设计。 比如 unraid 默认所有文件都属于 nobody:nusers 通过设置 PUID 和 PGID 就可以让容器运行之后的效果符合 unraid 的设计，这样就不需要额外的修复权限操作。
> 
> 而此前的版本最终生成的文件默认情况下属于 root 用户
> 
> 但是群晖很可能默认情况下，运行docker容器的用户不是root，也不是当前用户（具体是哪个用户因为我没用过群晖我也不知道），而默认建立文件夹的用户也不知道是哪个用户，所以我现在无法给你一个解决方案。

那为啥之前的版本都正常呢。。。

**Comment by VergilGao** [comment]
> > > > 你如果有条件，可以进终端打命令， id 命令可以获取你的 userid 和groupid，然后在环境变量里设置UID和GID，再原地输入命令 ··· mkdir test dd if=/dev/zero of="./test/MIFD-046.mp4" bs=250MB count=1 ··· 再输入 pwd 命令可以获取你现在的目录 然后你把这个目录下的 test 文件夹映射进去
> > > 
> > > 
> > > 看着有点懵。。。主要是我之前的版本一直是正常使用的，就昨天更新的版本突然用不了了
> > 
> > 
> > 因为不同的系统的文件权限设计不一样，我特意设置的 PUID 和 PGID 环境变量就是为了适应不同系统的文件权限设计。 比如 unraid 默认所有文件都属于 nobody:nusers 通过设置 PUID 和 PGID 就可以让容器运行之后的效果符合 unraid 的设计，这样就不需要额外的修复权限操作。
> > 而此前的版本最终生成的文件默认情况下属于 root 用户
> > 但是群晖很可能默认情况下，运行docker容器的用户不是root，也不是当前用户（具体是哪个用户因为我没用过群晖我也不知道），而默认建立文件夹的用户也不知道是哪个用户，所以我现在无法给你一个解决方案。
> 
> 那为啥之前的版本都正常呢。。。

因为之前的版本没有这个新设计啊。

**Comment by skypjsfly** [comment]
好像获取了目前用户的id然后填进去能用了，。。。。

**Comment by VergilGao** [comment]
我的nas最近刚迁移到unraid，所以设计上还是比较偏向于unraid，此外我对群晖一点都不了解，如果你能找到对群晖的权限系统由了解的人，应该能找到更好的解决方案

**Comment by skypjsfly** [comment]
现在能用，就是老报这种错误，之前的版本也这样，换了很多个梯子都是，我测试梯子是能访问这些网站的
![QQ截图20220210170132](https://user-images.githubusercontent.com/32484309/153373229-cd00a158-2cd5-4976-95d5-46e1dbfc91a3.png)

**Comment by VergilGao** [comment]
这个问题去主仓库求助吧，我这里只能解决docker运行的问题，实际软件运行的问题我解决不了，我也只是用户，不是软件的开发者。
