### ISSUE TITLE
rclone挂载google drive，刮削失败后无法移动到failed目录 & 以及超过200部影片容易触发内存溢出问题

### ISSUE THREAD

**Issue by tyhunter** [VergilGao/docker-mdc#45]
rclone 挂载命令如下：
rclone mount gd-xxxx: /root/rclone/xxxx --allow-other --allow-non-empty --umask 000 --daemon
docker命令如下：
/usr/bin/docker run --rm --name mdc_test -v /root/rclone/xxxx:/data -e SOURCE_FOLDER=./New -e SUCCESS_OUTPUT=./MDC/output -e FAILED_OUTPUT=./MDC/failed -e LOCATION_RULE="number" -e PUID=000 -e PGID=000 vergilgao/mdc:latest 

发现刮削成功可以移动到output目录，但是失败的时候无法移动到failed目录，提示：
'[-]Move to Failed output folder, see '/data/MDC/failed/where_was_i_before_being_moved.txt'
[-] [/data/New/IPX-840.mp4] ERROR:
[-] [Errno 1] Operation not permitted

以及超过200部影片容易触发内存溢出问题，这个没有来得及记下来报错的提示，看报错是Memory问题，在8G的机器和512M内存的机器上都会出现

**Comment by VergilGao** [comment]
去上游https://github.com/yoshiko2/Movie_Data_Capture反馈。
