### ISSUE TITLE
新构建的6.0.2版本刮削图片不会保存cdx.jpg了

### ISSUE THREAD

**Issue by skypjsfly** [VergilGao/docker-mdc#49]
以前有分卷的片子，每个分卷都会保存
xxxx-xxx-cdx.fanart.jpg
xxxx-xxx-cdx.thumb.jpg
xxxx-xxx-cdx.poster.jpg三个图片，
现在不管有多少分卷，都只保存
xxxx-xxx.fanart.jpg
xxxx-xxx.thumb.jpg
xxxx-xxx.poster.jpg
请问这是bug还是规则改了？附上新旧版本两张图。
![QQ截图20220315175530](https://user-images.githubusercontent.com/32484309/158352744-15ba3442-7922-41b5-81e6-0eec1f564df1.png)
![QQ截图20220315175539](https://user-images.githubusercontent.com/32484309/158352758-047906bd-3603-48fb-8d86-df21414fa2bc.png)

**Comment by VergilGao** [comment]
6.2.2-r0 已修复
