### ISSUE TITLE
视频识别，并整理好但是没有下载封面和nfo文件

### ISSUE THREAD

**Issue by yilin101** [VergilGao/docker-mdc#56]
视频识别，并整理好但是没有下载封面和nfo文件
[*]================= Movie Data Capture =================
[*]                        6.2.2                         
[*]======================================================
[*] - Linux-3.10.108-x86_64-with 
[*] - x86_64 - Python-3.9.13
[*]======================================================
[*] - 严禁在墙内宣传本项目 - 
[*]======================================================
[+]Start at 2022-05-28 17:08:09
[+]Load Config file '/config/mdc.ini'.
[+]Main Working mode ## 2: Organizing ## , nfo_skip_days=30
[+]Find 27 movies.
[*]======================================================
[!]               - 3.70% [1/27] -             17:08:12
[!] [BUR-435A] As Number Processing for '/data/JAV/BUR-435A.mkv'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb38.com', port=443): Max retries exceeded with url: /search?q=BUR-435A&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]               - 7.40% [2/27] -             17:09:28
[!] [BUR-435B] As Number Processing for '/data/JAV/BUR-435B.mkv'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb38.com', port=443): Max retries exceeded with url: /search?q=BUR-435B&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]               - 11.1% [3/27] -             17:10:43
[!] [BUR-435C] As Number Processing for '/data/JAV/BUR-435C.mkv'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb.com', port=443): Max retries exceeded with url: /search?q=BUR-435C&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]               - 14.8% [4/27] -             17:11:57
[!] [FC2-2497913] As Number Processing for '/data/JAV/FC2-PPV-2497913.mp4'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb38.com', port=443): Max retries exceeded with url: /search?q=FC2-2497913&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]               - 18.5% [5/27] -             17:13:37
[!] [FC2-2497913] As Number Processing for '/data/JAV/FC2-PPV-2497913_2.mp4'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb40.com', port=443): Max retries exceeded with url: /search?q=FC2-2497913&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]               - 22.2% [6/27] -             17:15:10
[!] [FLNS-113] As Number Processing for '/data/JAV/FLNS-113.mp4'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb.com', port=443): Max retries exceeded with url: /search?q=FLNS-113&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]               - 25.9% [7/27] -             17:16:28
[!] [FLNS-114] As Number Processing for '/data/JAV/FLNS-114.mp4'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb.com', port=443): Max retries exceeded with url: /search?q=FLNS-114&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]               - 29.6% [8/27] -             17:17:43
[!] [STARS-086] As Number Processing for '/data/JAV/STARS-086.mp4'
[+]Find movie [STARS-086] metadata on website 'javbus'
[-] [/data/JAV/STARS-086.mp4] ERROR:
[-] File Exists on destination path, we will never overwriting.
[!]               - 33.3% [9/27] -             17:18:02
[!] [GETCHU-4042103] As Number Processing for '/data/JAV/GETCHU-4042103/GETCHU-4042103.mp4'
[+]Find movie [GETCHU-4042103] metadata on website 'getchu'
[*]======================================================
[!]              - 37.0% [10/27] -             17:18:27
[!] [GETCHU-911772] As Number Processing for '/data/JAV/KADOKAWA/GETCHU-911772/GETCHU-911772.mp4'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb38.com', port=443): Max retries exceeded with url: /search?q=GETCHU-911772&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]              - 40.7% [11/27] -             17:19:36
[!] [SIRO-4823] As Number Processing for '/data/JAV/SIRO-4823/hhd800.com@SIRO-4823.mp4'
[+]Find movie [SIRO-4823] metadata on website 'mgstage'
[*]======================================================
[!]              - 44.4% [12/27] -             17:19:50
[!] [FC2-2552104] As Number Processing for '/data/JAV/deruデるking/FC2-2552104/FC2-2552104.mp4'
[+]Find movie [FC2-2552104] metadata on website 'fc2'
[*]======================================================
[!]              - 48.1% [13/27] -             17:20:27
[!] [zzpp01', 'com@mkck306b] As Number Processing for '/data/JAV/zzpp01.com@mkck306b/zzpp01.com@mkck306b.mp4'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb.com', port=443): Max retries exceeded with url: /search?q=ZZPP01',%20'COM@MKCK306B&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]              - 51.8% [14/27] -             17:21:44
[!] [APAA-382] As Number Processing for '/data/JAV/ひなた澪/APAA-382/APAA-382.mp4'
[+]Find movie [APAA-382] metadata on website 'javbus'
[*]======================================================
[!]              - 55.5% [15/27] -             17:22:08
[!] [GETCHU-984478] As Number Processing for '/data/JAV/キングレコード/GETCHU-984478/GETCHU-984478.mp4'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb39.com', port=443): Max retries exceeded with url: /search?q=GETCHU-984478&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]              - 59.2% [16/27] -             17:23:16
[!] [GETCHU-677570] As Number Processing for '/data/JAV/バンダイビジュアル/GETCHU-677570/GETCHU-677570.mp4'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb.com', port=443): Max retries exceeded with url: /search?q=GETCHU-677570&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]              - 62.9% [17/27] -             17:24:28
[!] [FSDSS-407] As Number Processing for '/data/JAV/夏木りん/FSDSS-407/FSDSS-407.mp4'
[+]Find movie [FSDSS-407] metadata on website 'javbus'
[*]======================================================
[!]              - 66.6% [18/27] -             17:24:51
[!] [STARS-576] As Number Processing for '/data/JAV/工藤ゆら/STARS-576/STARS-576.mp4'
[+]Find movie [STARS-576] metadata on website 'javbus'
[*]======================================================
[!]              - 70.3% [19/27] -             17:25:23
[!] [FSDSS-416] As Number Processing for '/data/JAV/時田亜美/FSDSS-416/FSDSS-416.mp4'
[+]Find movie [FSDSS-416] metadata on website 'javbus'
[*]======================================================
[!]              - 74.0% [20/27] -             17:25:46
[!] [FC2-2714057] As Number Processing for '/data/JAV/暗黒王子/FC2-2714057/FC2-2714057.mp4'
[+]Find movie [FC2-2714057] metadata on website 'fc2'
[*]======================================================
[!]              - 77.7% [21/27] -             17:26:21
[!] [STARS-562] As Number Processing for '/data/JAV/月乃ひな/STARS-562/STARS-562.mp4'
[+]Find movie [STARS-562] metadata on website 'javbus'
[*]======================================================
[!]              - 81.4% [22/27] -             17:26:44
[!] [PKPD-188] As Number Processing for '/data/JAV/根本佳澄/PKPD-188/PKPD-188.mp4'
[+]Find movie [PKPD-188] metadata on website 'javbus'
[*]======================================================
[!]              - 85.1% [23/27] -             17:27:08
[!] [KBI-073] As Number Processing for '/data/JAV/桂木凛/KBI-073/KBI-073-C.mp4'
[+]Find movie [KBI-073] metadata on website 'javbus'
[-] [/data/JAV/桂木凛/KBI-073/KBI-073-C.mp4] ERROR:
[-] [Errno 2] No such file or directory: 'JAV_output/桂木凛/KBI-073/KBI-073-C-thumb.jpg'
[!]              - 88.8% [24/27] -             17:27:30
[!] [KBI-076] As Number Processing for '/data/JAV/桂木凛/KBI-076/KBI-076.mp4'
[+]Find movie [KBI-076] metadata on website 'javbus'
[*]======================================================
[!]              - 92.5% [25/27] -             17:27:48
[!] [MEYD-033] As Number Processing for '/data/JAV/森沢かな（飯岡かなこ）/MEYD-033/MEYD-033-流出.mp4'
[+]Find movie [MEYD-033] metadata on website 'javbus'
[-] [/data/JAV/森沢かな（飯岡かなこ）/MEYD-033/MEYD-033-流出.mp4] ERROR:
[-] [Errno 2] No such file or directory: 'JAV_output/森沢かな（飯岡かなこ）/MEYD-033/MEYD-033-流出-thumb.jpg'
[!]              - 96.2% [26/27] -             17:28:15
[!] [DTT-093] As Number Processing for '/data/JAV/真木今日子/DTT-093/DTT-093.mp4'
[+]Find movie [DTT-093] metadata on website 'javbus'
[*]======================================================
[!]              - 100.% [27/27] -             17:28:35
[!] [FSDSS-448] As Number Processing for '/data/JAV/逢月ひまり/FSDSS-448/FSDSS-448.mp4'
[+]Find movie [FSDSS-448] metadata on website 'javbus'
[*]======================================================
[+]Deleting empty folder /data/JAV/GETCHU-4042103
[+]Deleting empty folder /data/JAV/SIRO-4823
[+]Deleting empty folder /data/JAV/deruデるking/FC2-2552104
[+]Deleting empty folder /data/JAV/deruデるking
[+]Deleting empty folder /data/JAV/ひなた澪/APAA-382
[+]Deleting empty folder /data/JAV/ひなた澪
[+]Deleting empty folder /data/JAV/夏木りん/FSDSS-407
[+]Deleting empty folder /data/JAV/夏木りん
[+]Deleting empty folder /data/JAV/工藤ゆら/STARS-576
[+]Deleting empty folder /data/JAV/工藤ゆら
[+]Deleting empty folder /data/JAV/時田亜美/FSDSS-416
[+]Deleting empty folder /data/JAV/時田亜美
[+]Deleting empty folder /data/JAV/暗黒王子/FC2-2714057
[+]Deleting empty folder /data/JAV/暗黒王子
[+]Deleting empty folder /data/JAV/月乃ひな/STARS-562
[+]Deleting empty folder /data/JAV/月乃ひな
[+]Deleting empty folder /data/JAV/根本佳澄/PKPD-188
[+]Deleting empty folder /data/JAV/根本佳澄
[+]Deleting empty folder /data/JAV/桂木凛/KBI-073
[+]Deleting empty folder /data/JAV/桂木凛/KBI-076
[+]Deleting empty folder /data/JAV/桂木凛
[+]Deleting empty folder /data/JAV/森沢かな（飯岡かなこ）/MEYD-033
[+]Deleting empty folder /data/JAV/森沢かな（飯岡かなこ）
[+]Deleting empty folder /data/JAV/真木今日子/DTT-093
[+]Deleting empty folder /data/JAV/真木今日子
[+]Deleting empty folder /data/JAV/逢月ひまり/FSDSS-448
[+]Deleting empty folder /data/JAV/逢月ひまり
[+]Deleting empty folder /data/failed
[+]Running time 0:21:14.506  End at 2022-05-28 17:29:24
[+]All finished!!!

**Comment by VergilGao** [comment]
你的运行参数是怎样的？
是全部都没有下载还是一部分没有下载，我看到前面几个视频在下载封面时似乎出现了网络错误。

**Comment by yilin101** [comment]
目前是全部的都下载不了，不知道哪个环节出错了 

之前一直用的是4.x 版本
最近几天发现更新了6.x了 就换成这个 而且配置里带有代理开关 感觉很不错 点个赞
 


# 详细教程请看
# - https://github.com/yoshiko2/Movie_Data_Capture/wiki#%E9%85%8D%E7%BD%AEconfigini
[common]
main_mode=2
source_folder=./
failed_output_folder=failed
success_output_folder=JAV_output
link_mode=0
; 0: 不刮削硬链接文件 1: 刮削硬链接文件
scan_hardlink=0
failed_move=0
auto_exit=0
translate_to_sc=0
multi_threading=0
;actor_gender value: female(♀) or male(♂) or both(♀ ♂) or all(♂ ♀ ⚧)
actor_gender=female
del_empty_folder=1
; 跳过最近(默认:30)天新修改过的.NFO，可避免整理模式(main_mode=3)和软连接(soft_link=0)时
; 反复刮削靠前的视频文件，0为处理所有视频文件
nfo_skip_days=30
ignore_failed_list=0
download_only_missing_images=1
mapping_table_validity=7
sleep=3

[advenced_sleep]
; 处理完多少个视频文件后停止，0为处理所有视频文件
stop_counter=0
; 再运行延迟时间，单位：h时m分s秒 举例: 1h30m45s(1小时30分45秒)  45(45秒)
; stop_counter不为零的条件下才有效，每处理stop_counter部影片后延迟rerun_delay秒再次运行
rerun_delay=0
; 以上参数配合使用可以以多次少量的方式刮削或整理数千个文件而不触发翻译或元数据站封禁

[proxy]
;proxytype: http or socks5 or socks5h switch: 0 1
switch=1
type=socks5h
proxy=x.x.x.x:xxx
timeout=20
retry=3
cacert_file=

[Name_Rule]
location_rule=actor+'/'+number
naming_rule=number+'-'+title
max_title_len=50

[update]
update_check=1

[priority]
website=javbus,airav,jav321,fanza,xcity,mgstage,fc2,avsox,dlsite,carib,madou,mv91,getchu,javdb,gcolle

[escape]
literals=\()/
folders=failed,JAV_output

[debug_mode]
switch=0

; 机器翻译
[translate]
switch=1
;可选项 google-free,azure
engine=google-free
; azure翻译密钥
key=
; 翻译延迟
delay=1
values=title,outline
service_site=translate.google.cn

; 预告片
[trailer]
switch=0

; 用来确定是否是无码
[uncensored]
uncensored_prefix=S2M,BT,LAF,SMD,SMBD,SM3D2DBD,SKY-,SKYHD,CWP,CWDV,CWBD,CW3D2DBD,MKD,MKBD,MXBD,MK3D2DBD,MCB3DBD,MCBD,RHJ,MMDV

[media]
; 影片后缀
media_type=.mp4,.avi,.rmvb,.wmv,.mov,.mkv,.flv,.ts,.webm,.iso,.mpg,.m4v
; 字幕后缀
sub_type=.smi,.srt,.idx,.sub,.sup,.psb,.ssa,.ass,.usf,.xss,.ssf,.rt,.lrc,.sbv,.vtt,.ttml

; 水印
[watermark]
switch=1
water=2
; 左上 0, 右上 1, 右下 2， 左下 3

; 剧照
[extrafanart]
switch=1
parallel_download=5
extrafanart_folder=extrafanart

; 剧情简介
[storyline]
switch=1
; website为javbus javdb avsox xcity carib时，site censored_site uncensored_site 为获取剧情简介信息的
; 可选数据源站点列表。列表内站点同时并发查询，取值优先级由冒号前的序号决定，从小到大，数字小的站点没数据才会采用后面站点获得的。
; 其中airavwiki airav avno1 58avgo是中文剧情简介，区别是airav只能查有码，avno1 airavwiki 有码无码都能查，
; 58avgo只能查无码或者流出破解马赛克的影片(此功能没使用)。
; xcity和amazon是日语的，由于amazon商城没有番号信息，选中对应DVD的准确率仅99.6%。如果三个列表全部为空则不查询，
; 设置成不查询可大幅提高刮削速度。
; site=
site=1:avno1,4:airavwiki
censored_site=2:airav,5:xcity,6:amazon
uncensored_site=3:58avgo
; 运行模式：0:顺序执行(最慢) 1:线程池(默认值) 2:进程池(启动开销比线程池大，并发站点越多越快)
run_mode=1
; show_result剧情简介调试信息 0关闭 1简略 2详细(详细部分不记入日志)，剧情简介失效时可打开2查看原因
show_result=0

; 繁简转换 繁简转换模式mode=0:不转换 1:繁转简 2:简转繁
[cc_convert]
mode=1
vars=outline,series,studio,tag,title

[javdb]
sites=38,39,40

; 人脸识别 locations_model=hog:方向梯度直方图(不太准确，速度快) cnn:深度学习模型(准确，需要GPU/CUDA,速度慢)
; uncensored_only=0:对全部封面进行人脸识别 1:只识别无码封面，有码封面直接切右半部分
; aways_imagecut=0:按各网站默认行为 1:总是裁剪封面，开启此项将无视[common]download_only_missing_images=1总是覆盖封面
; 封面裁剪的宽高比可配置，公式为aspect_ratio/3。默认aspect_ratio=2.12: 适配大部分有码影片封面，前一版本默认为2/3即aspect_ratio=2
[face]
locations_model=hog
uncensored_only=1
aways_imagecut=0
aspect_ratio=2.12

[jellyfin]
multi_part_fanart=0

[actor_photo]
download_for_kodi=0

**Comment by VergilGao** [comment]
```
[proxy]
;proxytype: http or socks5 or socks5h switch: 0 1
switch=1
type=socks5h
proxy=x.x.x.x:xxx
timeout=20
retry=3
cacert_file=
```
这里的代理设置的正确吗？
如果正确的话，我建议你先用 6.2.2-r0 这个版本，我的 6.2.2-r1 版本同步了上游最新的一个修复，似乎这个修复有些问题。
此外注意运行时的环境变量PUID 和 PGID已经更改为 UID 和 GID 了。

**Comment by yilin101** [comment]
> ```
> [proxy]
> ;proxytype: http or socks5 or socks5h switch: 0 1
> switch=1
> type=socks5h
> proxy=x.x.x.x:xxx
> timeout=20
> retry=3
> cacert_file=
> ```
> 
> 这里的代理设置的正确吗？ 如果正确的话，我建议你先用 6.2.2-r0 这个版本，我的 6.2.2-r1 版本同步了上游最新的一个修复，似乎这个修复有些问题。 此外注意运行时的环境变量PUID 和 PGID已经更改为 UID 和 GID 了。

这里是对的 因为是自己的服务器 所以隐藏了
我是运行在群晖的docker里 配置默认是UID gid 
我下载6.2.2-r0 试一下看看

**Comment by VergilGao** [comment]
所以6.2.2-r0有问题吗？因为我不用梯子所以测不了代理。

**Comment by yilin101** [comment]
> 所以6.2.2-r0有问题吗？因为我不用梯子所以测不了代理。

你好 也不行 只是整理了视频

**Comment by VergilGao** [comment]
> > 所以6.2.2-r0有问题吗？因为我不用梯子所以测不了代理。
> 
> 你好 也不行 只是整理了视频

好吧，我去联系上游作者。

**Comment by yilin101** [comment]
> > > 所以6.2.2-r0有问题吗？因为我不用梯子所以测不了代理。
> > 
> > 
> > 你好 也不行 只是整理了视频
> 
> 好吧，我去联系上游作者。

谢谢。辛苦了

**Comment by VergilGao** [comment]
是否有可能是代理本身的问题，能否在linux终端里尝试一下
```
curl --socks5-hostname xxx.xxx.xxx:xxx https://www.google.com/
```

**Comment by yilin101** [comment]
你好 mdc 的docker终端里面没法运行命令 
我在其他dokcer里面运行了一下 结果如下：
https://imgur.com/0YagVk0
https://imgur.com/Fye8nIp

**Comment by yilin101** [comment]
我复制了其中一部分 这样应该是正常的吧



 p {font-size: 20px; font-weight: 400; margin: 8px 0;}                                                                                                                                                   
    p, .attribution, {text-align: center;}                                                                                                                                                                  
    #spinner {margin: 0 auto 30px auto; display: block;}                                                                                                                                                    
    .attribution {margin-top: 32px;}                                                                                                                                                                        
    @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }                                                                                                                    
    @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }                                                                                                                
    #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}                                                                                                                                               
    #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}                                                                                                                                            
    #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}                                                                                                                                            
    .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }                                                                                 
    a { color: #2c7cb0; text-decoration: none; -moz-transition: color 0.15s ease; -o-transition: color 0.15s ease; -webkit-transition: color 0.15s ease; transition: color 0.15s ease; }                    
    a:hover{color: #f4a15d}                                                                                                                                                                                 
    .attribution{font-size: 16px; line-height: 1.5;}                                                                                                                                                        
    .ray_id{display: block; margin-top: 8px;}                                                                                                                                                               
    #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }                                                                                                                                  
    #cf-hcaptcha-container { text-align:center;}                                                                                                                                                            
    #cf-hcaptcha-container iframe { display: inline-block;}                                                                                                                                                 
  </style>                                                                                                                                                                                                  
                                                                                                                                                                                                            
      <meta http-equiv="refresh" content="35">                                                                                                                                                              
  <script>                                                                                                                                                                                                  
    //<![CDATA[                                                                                                                                                                                             
    (function(){                                                                                                                                                                                            
      window._cf_chl_opt={                                                                                                                                                                                  
        cvId: "2",                                                                                                                                                                                          
        cType: "non-interactive",                                                                                                                                                                           
        cNounce: "27505",                                                                                                                                                                                   
        cRay: "713c2a2e1dbd8b2f",                                                                                                                                                                           
        cHash: "b22cf08f21a28a5",                                                                                                                                                                           
        cUPMDTk: "\/search?q=BUR-435A&__cf_chl_tk=Z5.RZXiAPSg0LKmgmTavFlGLok7D5VMlUN3OCrLjBhI-1653962938-0-gaNycGzNByU",                                                                                    
        cFPWv: "b",                                                                                                                                                                                         
        cTTimeMs: "1000",                                                                                                                                                                                   
        cRq: {                                                                                                                                                                                              
          ru: "aHR0cHM6Ly9qYXZkYjM4LmNvbS9zZWFyY2g/cT1CVVItNDM1QQ==",                                                                                                                                       
          ra: "Y3VybC83Ljc5LjE=",                                                                                                                                                                           
          rm: "R0VU",                                                                                                                                                                                       
          d: "rEq8Il4bSXrvpZL9g7SCuoFAdySIDa4PUUJWPSZ47ZzlJxZCU85FljvSAESw4rLKDvVERpLBRu2ml9O2le8oTGsYdkVzNPbt+D22eMByglK3zXcbJVUHuF8b5YpMyR/CwYk59RummGDsCwA0TgN33k7Ypb5G5TXI4BLel+19rlCdeO4f3pg9pRuIcFIIs3
ta3Yo2q7Sa0wKb/XjZHfHy0rOjiqH1fynZ/rf27cyUK8h8TlV3EDfZp/m8M4rdmSJEKnsdscsQvtx1Tk1sRt8JOjUsjmCiWfwQ1bayGec3LZLiVQRVr/fiduzhAWfhh/T8xRD5bR58/cA2HHBnLkCCgijnN5M3zlUsc6ikSW187Z6LhfZYCDW8p4jMBL1KQE8p4lmGVOJhHj
0ifz1/UV8b0SrE/4ELKo+2yCRP7sgW0J86MuL9rpru8QdOED251OaZIRoH46iDaJJQXgD6rnsEhl4bONotmMT3Wp4ylwe4cBNs0hlFmRAD0gnsp79eSjD8ExdRxelSpLmcN0Oe8MaXxFDCvfTihgpzKKxJ+Ewk9/I=",                                        
          t: "MTY1Mzk2MjkzOC41NzUwMDA=",                                                                                                                                                                    
          m: "VATeAE4jlV98tmiN666Li5UgLtcYl7D9KdRxy9VVivs=",                                                                                                                                                
          i1: "Nma7OrlZxztR4nt9LmrIwA==",                                                                                                                                                                   
          i2: "vy/CAhp4djmGAwIJfaeEgA==",                                                                                                                                                                   
          zh: "pnup1jxI0T322AusPLVjFs6cvITjyWQ3fxsI0TpGuOQ=",                                                                                                                                               
          uh: "falndCMbwPZaI1tCsX87kuFM/7Evubc5zrKWaDOjabE=",

**Comment by VergilGao** [comment]
linux内核版本太低，请升级内核

**Comment by yilin101** [comment]
> > > linux内核版本太低，请升级内核
> > 
> > 
> > Docker啊？？？怎么升级内核？？？？
> 
> 你要升级你宿主机的内核啊 如果不懂的话，就将宿主机的系统更新到最新版本或者更换内核更新的linux发行版。 3.10这种内核跑python 3.9属实有点太难为python了

哦 我是群晖  不敢动这些操作  
这样子麻烦了

**Comment by yilin101** [comment]
旧版本能用代理吗

**Comment by yilin101** [comment]
群晖用旧版找到用法了 
设置dokcer的时候 添加以下环境变量：
USE_PROXY 1
PROXY_TYPE sock5
PROXY_URI 127.0.0.1:7890
