### ISSUE TITLE
无法刮削硬链接

### ISSUE THREAD

**Issue by henry-tujia** [VergilGao/docker-mdc#57]
## 问题描述

使用源代码`6.2.2-rc2`版，发现ini文件中，有可以设置的开关
```ini
; 0: 不刮削硬链接文件 1: 刮削硬链接文件
scan_hardlink=1
```
而docker版的ini中则没有，在实际运行时，出现了不识别硬链接的问题
![image](https://user-images.githubusercontent.com/69064655/172925519-8880e493-a6fb-4d0d-91fb-77ca5fe3fba6.png)

**Comment by VergilGao** [comment]
你需要重新pull一下，更新到6.2.2
此外注意更新之后新的部署方式，需要手动映射配置文件目录。

**Comment by VergilGao** [comment]
你 pull 的是 ghcr.io/vergilgao/mdc
运行的是 vergilgao/mdc

**Comment by henry-tujia** [comment]
> 你 pull 的是 ghcr.io/vergilgao/mdc 运行的是 vergilgao/mdc

okok,解决了，谢谢您
