### ISSUE TITLE
提个教程建议

### ISSUE THREAD

**Issue by laowangdegit** [VergilGao/docker-mdc#59]
映射的data和config最好再同一个文件夹，至少群辉是这样才能运行，而且原版软件就是配置文件和运行文件在媒体库才行。我看前面也有兄弟用的是别的什么设备也是这个问题，所以介绍里最好加上这条吧

**Comment by VergilGao** [comment]
不建议用同一个文件夹，这样可以多文件夹刮削。

**Comment by laowangdegit** [comment]
你没有懂我的意思，不在一个文件夹他在有的客户端不能运行，我群辉是这样，历史问题里有个极空间也是

**Comment by VergilGao** [comment]
极空间那个和这个没有关系
