### ISSUE TITLE
docker版本无法识别硬链接的影片

### ISSUE THREAD

**Issue by DeroOneeee** [VergilGao/docker-mdc#60]
作者您好，首先感谢技术输出，我的影片都存在nas上，实在是不想每次都开window再运行刮削，所以今天使用了您的docker版本，但是遇到一个问题，情况如下。
背景：
为了PT站做种，我对所有下载的影片进行了硬链接指向A文件夹。
windows版本，局域网访问A文件夹，运行exe，可以识别到影片并顺利运行。
docker版本，将装载文件夹设置好后，装载文件夹和硬盘文件夹在同一个硬盘内。
1.将A文件夹的文件**剪切**到data文件夹下，运行程序，正常运行，提示找到0个影片，随后自动关闭。
2.将A文件夹的文件**复制**到data文件夹下，此时会有复制影片写入硬盘的过程，运行程序，正常运行，能够正常识别到影片并进行刮削。
可以复现问题，请问是否是因为A文件夹是实际媒体文件的硬链接导致的识别不到影片？

**Comment by VergilGao** [comment]
设置里应该是有支持硬链接的选项的。

**Comment by DeroOneeee** [comment]
> 设置里应该是有支持硬链接的选项的。
> 
> ```
> scan_hardlink=1
> ```

啊，确实有这个选项，现在已经可以对迁移而非复制过来的硬链接媒体进行刮削了，实在是没什么代码基础，没有去阅读源码的ini，抱歉添麻烦啦，谢谢啦

**Comment by VergilGao** [comment]
上游有配置文件说明：
https://github.com/yoshiko2/Movie_Data_Capture/wiki
