### ISSUE TITLE
影片目录如果存在配置文件，则手动映射的配置文件无效

### ISSUE THREAD

**Issue by wmgylc** [VergilGao/docker-mdc#62]
如题。

在解决nas服务器的j4125无法使用人脸识别的时候发现，mdc.ini置空对应的locations_model无效，而在对应影片目录的config.ini中将locations_model置空，则可以顺利识别不会出现程序崩溃。

**Comment by VergilGao** [comment]
根据上游wiki，配置文件优先级：
```
./config.ini
~/mdc.ini
~/.mdc.ini
~/.mdc/config.ini
~/.config/mdc/config.ini
```
