### ISSUE TITLE
INTERNAL ERROR: cannot create temporary directory!

### ISSUE THREAD

**Issue by NimbuSHh** [VergilGao/docker-mdc#65]
Qnap的Nas上跑，不管是通过Container还是命令行，都是INTERNAL ERROR: cannot create temporary directory!
这报错也没啥信息量，怎么解决啊~

---Setup Timezone to Asia/Shanghai---
---Checking if UID: 99 matches user---
---Checking if GID: 100 matches user---
usermod: no changes
---Setting umask to 002---
---Taking ownership of data...---
Checking if config file exist
Starting...
[15] INTERNAL ERROR: cannot create temporary directory!

**Comment by Hansen1018** [comment]
我也是相同问题，不知道为啥

**Comment by VergilGao** [comment]
用户无权限创建文件夹，可能是操作系统对用户拥有的数据容量做了限制。

**Comment by Hansen1018** [comment]
> 用户无权限创建文件夹，可能是操作系统对用户拥有的数据容量做了限制。

前几天用的还正常，前几天有一块硬盘出现警告，重新建立了后两个储存池就这样，删除容器重新拉取都无法使用

**Comment by VergilGao** [comment]
> 


这是pyinstaller在尝试解压程序到临时目录，这个临时目录占用的是docker自己的文件系统空间，如果有限额，自然就无法解压。
你看看你自己的docker设置，各种系统设置吧。
或者打威联通售后电话。

**Comment by VergilGao** [comment]
当前程序打包已经从单文件模式改为目录模式。
可以尝试一下是否还会出现相同的问题。

**Comment by Hansen1018** [comment]
从上次反馈后，我尝试重启NAS解决问题。
之后不知道哪个版本无法刮搜，没有管，昨天重新最新版本恢复正常了。
