### ISSUE TITLE
群晖 装好扫不出文件是为啥呢？

### ISSUE THREAD

**Issue by Colco** [VergilGao/docker-mdc#66]
[*]================= Movie Data Capture =================
[*]                        6.4.1                         
[*]======================================================
[*] - Linux-4.4.180+-x86_64-with 
[*] - x86_64 - Python-3.10.8
[+]Start at 2022-12-11 23:57:12
[+]Load Config file '/config/mdc.ini'.
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[+]Find 0 movies.
[*]======================================================
[+]Deleting empty folder /data/failed
[+]Running time 0:00:00.548  End at 2022-12-11 23:57:12
[+]All finished!!!

**Comment by VergilGao** [comment]
linux内核版本太低。

**Comment by anooki-c** [comment]
我的也是这个提示，黑裙7.0，要怎么升级linux内核版本啊
