### ISSUE TITLE
Docker中没法建立soft link？

### ISSUE THREAD

**Issue by ganganray** [VergilGao/docker-mdc#73]
我将希望处理的文件夹挂在到docker容器，可以正常下载图片创建nfo文件，但是无法在docker外的实体文件夹创建软连接。请问有没有处理的方法？

**Comment by VergilGao** [comment]
没太懂你的意思，可以描述的再详细些吗？

**Comment by ganganray** [comment]
我在群晖中创建了MDC的docker容器，link_mode = 1，希望建立软连接，不影响PT目录的源文件。创建容器的时候我设置了文件夹的映射，例如把容器中的/source映射为NAS实际中存放片子的目录（例如外面的/home/user/av），把容器中的/output映射为NAS存方刮削图片、信息和软连接的目录（例如外面的/home/user/av_data）。

MDC的设置为：
```
source_folder = /source
success_output_folder = /output
link_mode = 1
```
运行后能刮削信息、图片并存储在容器的/output目录中，也就是nas上的真实目录中。但是软连接并没有出现在真实目录中。我尝试用
`docker exec -it movie_data_capture ls output/xxx/xxx-xxx`
列出容器中刮削好的目录里的文件，是建立了软连接的（估计就是从/output指向/source的软连接），但在外面真实目录中没有（我怀疑即使有也会错误地指向/output文件夹，而不是我希望的/home/user/av）。
不知道docker原则上是否可能为外面的真实目录建立软连接？

**Comment by VergilGao** [comment]
docker不支持你这样的操作
