### ISSUE TITLE
 请问旁路由模式下如何使用代理？

### ISSUE THREAD

**Issue by madwood123** [VergilGao/docker-mdc#75]
NAS网关为主路由的0.1，没有全局科学上网环境，旁路由网关为.100，mcd中填写旁路由网关ip以及Openclash的7890端口无法刮削，容器反复重启。

**Comment by VergilGao** [comment]
有日志吗？

**Comment by madwood123** [comment]
> 有日志吗？
      W2023-03-21T01:40:29.704764566Z [!]                - 100.% [4/4] -             09:34:35
      ^2023-03-21T01:40:29.704961507Z [!] [SSIS-604] As Number Processing for '/data/SSIS-604-C.mp4'
      C2023-03-21T01:40:29.705045084Z [-]Movie Number or Title not found!
      Y2023-03-21T01:40:29.705134605Z [*]======================================================
      W2023-03-21T01:40:29.705236176Z [+]Running time 0:23:28.827  End at 2023-03-21 09:40:29
      22023-03-21T01:40:29.705339942Z [+]All finished!!!
      X2023-03-21T01:40:29.705436564Z Log file '/config/.mlogs/mdc_20230321T091700.txt' saved.
      E2023-03-21T01:40:32.614276285Z ---Setup Timezone to Asia/Shanghai---
      E2023-03-21T01:40:32.614720578Z ---Checking if UID: 0 matches user---
      32023-03-21T01:40:32.636879702Z usermod: no changes
      E2023-03-21T01:40:32.637105269Z ---Checking if GID: 0 matches user---
      32023-03-21T01:40:32.806138380Z usermod: no changes
      ;2023-03-21T01:40:32.806462612Z ---Setting umask to 0022---
      A2023-03-21T01:40:32.806606092Z ---Taking ownership of data...---
      =2023-03-21T01:40:57.031745332Z Checking if config file exist
      +2023-03-21T01:40:57.031956741Z Starting...
      Y2023-03-21T02:08:06.329717344Z [*]================= Movie Data Capture =================
      Y2023-03-21T02:08:06.330110621Z [*]                        6.5.2                         
      Y2023-03-21T02:08:06.330471626Z [*]======================================================
      K2023-03-21T02:08:06.330709989Z [*] - Linux-5.8.18-z4-generic+-x86_64-with 
      =2023-03-21T02:08:06.330875230Z [*] - x86_64 - Python-3.10.10
      Y2023-03-21T02:08:06.330985846Z [*]======================================================
      G2023-03-21T02:08:06.331072283Z [*] - 严禁在墙内宣传本项目 - 
      Y2023-03-21T02:08:06.331161303Z [*]======================================================
      ?2023-03-21T02:08:06.331258978Z [+]Start at 2023-03-21 09:41:09
      G2023-03-21T02:08:06.331361049Z [+]Load Config file '/data/config.ini'.
      Y2023-03-21T02:08:06.331448123Z [+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
      12023-03-21T02:08:06.331529339Z [+]Find 4 movies.
      Y2023-03-21T02:08:06.331609522Z [*]======================================================
      W2023-03-21T02:08:06.331693059Z [!]                - 25.0% [1/4] -             09:41:16
      ^2023-03-21T02:08:06.331772321Z [!] [IPZZ-008] As Number Processing for '/data/IPZZ-008-C.mp4'
      C2023-03-21T02:08:06.331855778Z [-]Movie Number or Title not found!
      Y2023-03-21T02:08:06.331935878Z [*]======================================================
      W2023-03-21T02:08:06.332021690Z [!]                - 50.0% [2/4] -             09:47:43
      ^2023-03-21T02:08:06.332115069Z [!] [IPZZ-004] As Number Processing for '/data/IPZZ-004-C.mp4'
     <2023-03-21T02:08:06.332212603Z [-]get_html_by_form() Failed! HTTPSConnectionPool(host='xcity.jp', port=443): Max retries exceeded with url: /policy/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd8f0250b20>: Failed to establish a new connection: [Errno 101] Network unreachable'))
      C2023-03-21T02:08:06.332300471Z [-]Movie Number or Title not found!
      Y2023-03-21T02:08:06.332391829Z [*]======================================================
      W2023-03-21T02:08:06.332489687Z [!]                - 75.0% [3/4] -             09:54:55
      ^2023-03-21T02:08:06.332587786Z [!] [IPZZ-009] As Number Processing for '/data/IPZZ-009-C.mp4'
     92023-03-21T02:08:06.332678931Z [-]get_html_by_form() Failed! HTTPSConnectionPool(host='xcity.jp', port=443): Max retries exceeded with url: /law/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd8f0252a10>: Failed to establish a new connection: [Errno 101] Network unreachable'))
      C2023-03-21T02:08:06.332809865Z [-]Movie Number or Title not found!
      Y2023-03-21T02:08:06.332896756Z [*]======================================================
      W2023-03-21T02:08:06.332977565Z [!]                - 100.% [4/4] -             10:02:07
      ^2023-03-21T02:08:06.333056047Z [!] [SSIS-604] As Number Processing for '/data/SSIS-604-C.mp4'
      C2023-03-21T02:08:06.333135357Z [-]Movie Number or Title not found!
      Y2023-03-21T02:08:06.333218509Z [*]======================================================
      W2023-03-21T02:08:06.333316229Z [+]Running time 0:26:56.354  End at 2023-03-21 10:08:06
      22023-03-21T02:08:06.333401227Z [+]All finished!!!
      X2023-03-21T02:08:06.333685515Z Log file '/config/.mlogs/mdc_20230321T094109.txt' saved.
      E2023-03-21T02:08:09.242042438Z ---Setup Timezone to Asia/Shanghai---
      E2023-03-21T02:08:09.242575119Z ---Checking if UID: 0 matches user---
      32023-03-21T02:08:09.285963608Z usermod: no changes
      E2023-03-21T02:08:09.286151954Z ---Checking if GID: 0 matches user---
      32023-03-21T02:08:09.441828228Z usermod: no changes
      ;2023-03-21T02:08:09.442163649Z ---Setting umask to 0022---
      A2023-03-21T02:08:09.442314637Z ---Taking ownership of data...---
      =2023-03-21T02:08:33.825185979Z Checking if config file exist
      +2023-03-21T02:08:33.825612509Z Starting...
      Y2023-03-21T02:33:56.832340693Z [*]================= Movie Data Capture =================
      Y2023-03-21T02:33:56.832603897Z [*]                        6.5.2                         
      Y2023-03-21T02:33:56.832746376Z [*]======================================================
      K2023-03-21T02:33:56.832835991Z [*] - Linux-5.8.18-z4-generic+-x86_64-with 
      =2023-03-21T02:33:56.832940170Z [*] - x86_64 - Python-3.10.10
      Y2023-03-21T02:33:56.833024929Z [*]======================================================
      G2023-03-21T02:33:56.833115279Z [*] - 严禁在墙内宣传本项目 - 
      Y2023-03-21T02:33:56.833197403Z [*]======================================================
      ?2023-03-21T02:33:56.833315946Z [+]Start at 2023-03-21 10:08:47
      G2023-03-21T02:33:56.833401195Z [+]Load Config file '/data/config.ini'.
      Y2023-03-21T02:33:56.833492224Z [+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
      12023-03-21T02:33:56.833575432Z [+]Find 4 movies.
      Y2023-03-21T02:33:56.833670720Z [*]======================================================
      W2023-03-21T02:33:56.833763509Z [!]                - 25.0% [1/4] -             10:08:54
      ^2023-03-21T02:33:56.833843636Z [!] [IPZZ-008] As Number Processing for '/data/IPZZ-008-C.mp4'
      C2023-03-21T02:33:56.833926725Z [-]Movie Number or Title not found!
      Y2023-03-21T02:33:56.834007640Z [*]======================================================
      W2023-03-21T02:33:56.834088267Z [!]                - 50.0% [2/4] -             10:14:27
      ^2023-03-21T02:33:56.834205463Z [!] [IPZZ-004] As Number Processing for '/data/IPZZ-004-C.mp4'
      C2023-03-21T02:33:56.834292728Z [-]Movie Number or Title not found!
      Y2023-03-21T02:33:56.834375672Z [*]======================================================
      W2023-03-21T02:33:56.834460842Z [!]                - 75.0% [3/4] -             10:20:56
      ^2023-03-21T02:33:56.834538981Z [!] [IPZZ-009] As Number Processing for '/data/IPZZ-009-C.mp4'
      C2023-03-21T02:33:56.834620665Z [-]Movie Number or Title not found!
      Y2023-03-21T02:33:56.834702408Z [*]======================================================
      W2023-03-21T02:33:56.834786735Z [!]                - 100.% [4/4] -             10:27:25
      ^2023-03-21T02:33:56.834871005Z [!] [SSIS-604] As Number Processing for '/data/SSIS-604-C.mp4'
      C2023-03-21T02:33:56.834952338Z [-]Movie Number or Title not found!
      Y2023-03-21T02:33:56.835033776Z [*]======================================================
      W2023-03-21T02:33:56.835112709Z [+]Running time 0:25:09.551  End at 2023-03-21 10:33:56
      22023-03-21T02:33:56.835199354Z [+]All finished!!!
      X2023-03-21T02:33:56.835286105Z Log file '/config/.mlogs/mdc_20230321T100846.txt' saved.
      E2023-03-21T02:33:59.739447278Z ---Setup Timezone to Asia/Shanghai---
      E2023-03-21T02:33:59.740244586Z ---Checking if UID: 0 matches user---
      32023-03-21T02:33:59.774076865Z usermod: no changes
      E2023-03-21T02:33:59.774320095Z ---Checking if GID: 0 matches user---
      32023-03-21T02:33:59.921332085Z usermod: no changes
      ;2023-03-21T02:33:59.921654071Z ---Setting umask to 0022---
      A2023-03-21T02:33:59.921762867Z ---Taking ownership of data...---
      =2023-03-21T02:34:24.810708782Z Checking if config file exist
      +2023-03-21T02:34:24.810904397Z Starting...

**Comment by madwood123** [comment]
> 有日志吗？

      W2023-03-21T01:40:29.704764566Z [!]                - 100.% [4/4] -             09:34:35
      ^2023-03-21T01:40:29.704961507Z [!] [SSIS-604] As Number Processing for '/data/SSIS-604-C.mp4'
      C2023-03-21T01:40:29.705045084Z [-]Movie Number or Title not found!
      Y2023-03-21T01:40:29.705134605Z [*]======================================================
      W2023-03-21T01:40:29.705236176Z [+]Running time 0:23:28.827  End at 2023-03-21 09:40:29
      22023-03-21T01:40:29.705339942Z [+]All finished!!!
      X2023-03-21T01:40:29.705436564Z Log file '/config/.mlogs/mdc_20230321T091700.txt' saved.
      E2023-03-21T01:40:32.614276285Z ---Setup Timezone to Asia/Shanghai---
      E2023-03-21T01:40:32.614720578Z ---Checking if UID: 0 matches user---
      32023-03-21T01:40:32.636879702Z usermod: no changes
      E2023-03-21T01:40:32.637105269Z ---Checking if GID: 0 matches user---
      32023-03-21T01:40:32.806138380Z usermod: no changes
      ;2023-03-21T01:40:32.806462612Z ---Setting umask to 0022---
      A2023-03-21T01:40:32.806606092Z ---Taking ownership of data...---
      =2023-03-21T01:40:57.031745332Z Checking if config file exist
      +2023-03-21T01:40:57.031956741Z Starting...
      Y2023-03-21T02:08:06.329717344Z [*]================= Movie Data Capture =================
      Y2023-03-21T02:08:06.330110621Z [*]                        6.5.2                         
      Y2023-03-21T02:08:06.330471626Z [*]======================================================
      K2023-03-21T02:08:06.330709989Z [*] - Linux-5.8.18-z4-generic+-x86_64-with 
      =2023-03-21T02:08:06.330875230Z [*] - x86_64 - Python-3.10.10
      Y2023-03-21T02:08:06.330985846Z [*]======================================================
      G2023-03-21T02:08:06.331072283Z [*] - 严禁在墙内宣传本项目 - 
      Y2023-03-21T02:08:06.331161303Z [*]======================================================
      ?2023-03-21T02:08:06.331258978Z [+]Start at 2023-03-21 09:41:09
      G2023-03-21T02:08:06.331361049Z [+]Load Config file '/data/config.ini'.
      Y2023-03-21T02:08:06.331448123Z [+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
      12023-03-21T02:08:06.331529339Z [+]Find 4 movies.
      Y2023-03-21T02:08:06.331609522Z [*]======================================================
      W2023-03-21T02:08:06.331693059Z [!]                - 25.0% [1/4] -             09:41:16
      ^2023-03-21T02:08:06.331772321Z [!] [IPZZ-008] As Number Processing for '/data/IPZZ-008-C.mp4'
      C2023-03-21T02:08:06.331855778Z [-]Movie Number or Title not found!
      Y2023-03-21T02:08:06.331935878Z [*]======================================================
      W2023-03-21T02:08:06.332021690Z [!]                - 50.0% [2/4] -             09:47:43
      ^2023-03-21T02:08:06.332115069Z [!] [IPZZ-004] As Number Processing for '/data/IPZZ-004-C.mp4'
     <2023-03-21T02:08:06.332212603Z [-]get_html_by_form() Failed! HTTPSConnectionPool(host='xcity.jp', port=443): Max retries exceeded with url: /policy/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd8f0250b20>: Failed to establish a new connection: [Errno 101] Network unreachable'))
      C2023-03-21T02:08:06.332300471Z [-]Movie Number or Title not found!
      Y2023-03-21T02:08:06.332391829Z [*]======================================================
      W2023-03-21T02:08:06.332489687Z [!]                - 75.0% [3/4] -             09:54:55
      ^2023-03-21T02:08:06.332587786Z [!] [IPZZ-009] As Number Processing for '/data/IPZZ-009-C.mp4'
     92023-03-21T02:08:06.332678931Z [-]get_html_by_form() Failed! HTTPSConnectionPool(host='xcity.jp', port=443): Max retries exceeded with url: /law/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd8f0252a10>: Failed to establish a new connection: [Errno 101] Network unreachable'))
      C2023-03-21T02:08:06.332809865Z [-]Movie Number or Title not found!
      Y2023-03-21T02:08:06.332896756Z [*]======================================================
      W2023-03-21T02:08:06.332977565Z [!]                - 100.% [4/4] -             10:02:07
      ^2023-03-21T02:08:06.333056047Z [!] [SSIS-604] As Number Processing for '/data/SSIS-604-C.mp4'
      C2023-03-21T02:08:06.333135357Z [-]Movie Number or Title not found!
      Y2023-03-21T02:08:06.333218509Z [*]======================================================
      W2023-03-21T02:08:06.333316229Z [+]Running time 0:26:56.354  End at 2023-03-21 10:08:06
      22023-03-21T02:08:06.333401227Z [+]All finished!!!
      X2023-03-21T02:08:06.333685515Z Log file '/config/.mlogs/mdc_20230321T094109.txt' saved.
      E2023-03-21T02:08:09.242042438Z ---Setup Timezone to Asia/Shanghai---
      E2023-03-21T02:08:09.242575119Z ---Checking if UID: 0 matches user---
      32023-03-21T02:08:09.285963608Z usermod: no changes
      E2023-03-21T02:08:09.286151954Z ---Checking if GID: 0 matches user---
      32023-03-21T02:08:09.441828228Z usermod: no changes
      ;2023-03-21T02:08:09.442163649Z ---Setting umask to 0022---
      A2023-03-21T02:08:09.442314637Z ---Taking ownership of data...---
      =2023-03-21T02:08:33.825185979Z Checking if config file exist
      +2023-03-21T02:08:33.825612509Z Starting...
      Y2023-03-21T02:33:56.832340693Z [*]================= Movie Data Capture =================
      Y2023-03-21T02:33:56.832603897Z [*]                        6.5.2                         
      Y2023-03-21T02:33:56.832746376Z [*]======================================================
      K2023-03-21T02:33:56.832835991Z [*] - Linux-5.8.18-z4-generic+-x86_64-with 
      =2023-03-21T02:33:56.832940170Z [*] - x86_64 - Python-3.10.10
      Y2023-03-21T02:33:56.833024929Z [*]======================================================
      G2023-03-21T02:33:56.833115279Z [*] - 严禁在墙内宣传本项目 - 
      Y2023-03-21T02:33:56.833197403Z [*]======================================================
      ?2023-03-21T02:33:56.833315946Z [+]Start at 2023-03-21 10:08:47
      G2023-03-21T02:33:56.833401195Z [+]Load Config file '/data/config.ini'.
      Y2023-03-21T02:33:56.833492224Z [+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
      12023-03-21T02:33:56.833575432Z [+]Find 4 movies.
      Y2023-03-21T02:33:56.833670720Z [*]======================================================
      W2023-03-21T02:33:56.833763509Z [!]                - 25.0% [1/4] -             10:08:54
      ^2023-03-21T02:33:56.833843636Z [!] [IPZZ-008] As Number Processing for '/data/IPZZ-008-C.mp4'
      C2023-03-21T02:33:56.833926725Z [-]Movie Number or Title not found!
      Y2023-03-21T02:33:56.834007640Z [*]======================================================
      W2023-03-21T02:33:56.834088267Z [!]                - 50.0% [2/4] -             10:14:27
      ^2023-03-21T02:33:56.834205463Z [!] [IPZZ-004] As Number Processing for '/data/IPZZ-004-C.mp4'
      C2023-03-21T02:33:56.834292728Z [-]Movie Number or Title not found!
      Y2023-03-21T02:33:56.834375672Z [*]======================================================
      W2023-03-21T02:33:56.834460842Z [!]                - 75.0% [3/4] -             10:20:56
      ^2023-03-21T02:33:56.834538981Z [!] [IPZZ-009] As Number Processing for '/data/IPZZ-009-C.mp4'
      C2023-03-21T02:33:56.834620665Z [-]Movie Number or Title not found!
      Y2023-03-21T02:33:56.834702408Z [*]======================================================
      W2023-03-21T02:33:56.834786735Z [!]                - 100.% [4/4] -             10:27:25
      ^2023-03-21T02:33:56.834871005Z [!] [SSIS-604] As Number Processing for '/data/SSIS-604-C.mp4'
      C2023-03-21T02:33:56.834952338Z [-]Movie Number or Title not found!
      Y2023-03-21T02:33:56.835033776Z [*]======================================================
      W2023-03-21T02:33:56.835112709Z [+]Running time 0:25:09.551  End at 2023-03-21 10:33:56
      22023-03-21T02:33:56.835199354Z [+]All finished!!!
      X2023-03-21T02:33:56.835286105Z Log file '/config/.mlogs/mdc_20230321T100846.txt' saved.
      E2023-03-21T02:33:59.739447278Z ---Setup Timezone to Asia/Shanghai---
      E2023-03-21T02:33:59.740244586Z ---Checking if UID: 0 matches user---
      32023-03-21T02:33:59.774076865Z usermod: no changes
      E2023-03-21T02:33:59.774320095Z ---Checking if GID: 0 matches user---
      32023-03-21T02:33:59.921332085Z usermod: no changes
      ;2023-03-21T02:33:59.921654071Z ---Setting umask to 0022---
      A2023-03-21T02:33:59.921762867Z ---Taking ownership of data...---
      =2023-03-21T02:34:24.810708782Z Checking if config file exist
      +2023-03-21T02:34:24.810904397Z Starting...

**Comment by VergilGao** [comment]
你可以用 --network =host 参数让docker使用主机的ip地址，默认的桥接模式可能找不到你的旁路由。

**Comment by VergilGao** [comment]
Network unreachable 还是找不到你的旁路由
