### ISSUE TITLE
群晖docker报Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by mingminghua** [VergilGao/docker-mdc#77]
系统：群晖7
问题：docker通过命令测试成功，但是配置了实际的文件目录后，命令启动报错了，求解
日志如下：
---Setting umask to 002---
---Taking ownership of data...---
Checking if config file exist
Starting...
[*]================= Movie Data Capture =================
[*]                        6.5.2                         
[*]======================================================
[*] - Linux-4.4.180+-x86_64-with 
[*] - x86_64 - Python-3.10.10
[*]======================================================
[*] - 严禁在墙内宣传本项目 - 
[*]======================================================
[+]Start at 2023-03-23 21:34:01
[+]Load Config file '/config/mdc.ini'.
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[+]Find 3748 movies.
[*]======================================================
[!]             - 0.02% [1/3748] -             21:34:06
[!] [HEYZO-1554] As Number Processing for '/data/2048论坛@fun2048.com -heyzo_hd_1554_full.mp4'
[-]get_html_by_scraper() failed. HTTPConnectionPool(host='javhq.tv', port=80): Max retries exceeded with url: /cn/search.php?kw_type=key&kw=HEYZO-1554 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f47e1ca7760>: Failed to establish a new connection: [Errno 111] Connection refused'))
Illegal instruction (core dumped)

**Comment by VergilGao** [comment]
配置文件里关掉人脸识别
