### ISSUE TITLE
请问大大，版本号有6.6.3-r1和6.6.3有什么区别？r1代表什么呢？？

### ISSUE THREAD

**Issue by heptagonlin** [VergilGao/docker-mdc#81]
请问大大，版本号有6.6.3-r1和6.6.3有什么区别？r1代表什么呢？？

**Comment by VergilGao** [comment]
r1 就是 6.6.3 版本第二次发布的 docker 镜像。
r0 是第一次，但是那次发布的有问题所以在列表里没有。
具体可以看 docker 镜像的 tag 规则。
